apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: crypto-watch-00001-vwb
  namespace: '819879407905'
  selfLink: /apis/serving.knative.dev/v1/namespaces/819879407905/revisions/crypto-watch-00001-vwb
  uid: 13008b46-2b6c-4014-8f30-d37d86bfbf80
  resourceVersion: AAYoPY2kR8w
  generation: 1
  creationTimestamp: '2024-12-01T23:10:29.759870Z'
  labels:
    serving.knative.dev/configuration: crypto-watch
    serving.knative.dev/configurationGeneration: '1'
    serving.knative.dev/service: crypto-watch
    serving.knative.dev/serviceUid: d9666dde-017c-4d6e-a3af-f9cdea217e48
    serving.knative.dev/route: crypto-watch
    cloud.googleapis.com/location: us-south1
    run.googleapis.com/startupProbeType: Default
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/startup-cpu-boost: 'true'
    run.googleapis.com/execution-environment: gen1
    run.googleapis.com/operation-id: c2f7567c-395c-48c9-9390-bb6bfdac20b7
    autoscaling.knative.dev/maxScale: '100'
    serving.knative.dev/creator: caiohenriquefreiree@gmail.com
  ownerReferences:
  - kind: Configuration
    name: crypto-watch
    uid: 31b40415-e3ea-4023-a6b9-931ac5532a0b
    apiVersion: serving.knative.dev/v1
    controller: true
    blockOwnerDeletion: true
spec:
  containerConcurrency: 80
  timeoutSeconds: 3600
  serviceAccountName: 819879407905-compute@developer.gserviceaccount.com
  containers:
  - name: crypto-container
    image: gcr.io/cloudrun/placeholder@sha256:4556354a729f7903d83bb125d6b1d8fb433dfe4e279e1d27dc5358431910a3fd
    ports:
    - name: http1
      containerPort: 8080
    env:
    - name: URL_TICKERS
      value: https://api.coinpaprika.com/v1/tickers?limit=31&quotes=brl,usd
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
    startupProbe:
      timeoutSeconds: 240
      periodSeconds: 240
      failureThreshold: 1
      tcpSocket:
        port: 8080
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-12-01T23:11:33.518260Z'
  - type: Active
    status: 'True'
    lastTransitionTime: '2024-12-01T23:11:33.573503Z'
    severity: Info
  - type: ContainerHealthy
    status: 'True'
    message: Container became healthy.
    lastTransitionTime: '2024-12-01T23:11:33.485875Z'
  - type: ContainerReady
    status: 'True'
    message: Container image import completed in 1.127379s.
    lastTransitionTime: '2024-12-01T23:11:30.635483Z'
  - type: ResourcesAvailable
    status: 'True'
    message: Revision deployment finished in 2.593603s. Checking container health.
    lastTransitionTime: '2024-12-01T23:11:33.226417Z'
  logUrl: https://console.cloud.google.com/logs/viewer?project=atomic-shine-443421-h0&resource=cloud_run_revision/service_name/crypto-watch/revision_name/crypto-watch-00001-vwb&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22crypto-watch%22%0Aresource.labels.revision_name%3D%22crypto-watch-00001-vwb%22
  imageDigest: gcr.io/cloudrun/placeholder@sha256:4556354a729f7903d83bb125d6b1d8fb433dfe4e279e1d27dc5358431910a3fd
  containerStatuses:
  - name: crypto-container
    imageDigest: gcr.io/cloudrun/placeholder@sha256:4556354a729f7903d83bb125d6b1d8fb433dfe4e279e1d27dc5358431910a3fd
